from django.urls import path
from . import views
from .views import download_medical_records_pdf


urlpatterns = [
    path("test_token/", views.user_token_auth),
    path("signup/", views.user_signup),
    path("login/", views.user_login),
    path("setup_provider/", views.setup_provider),
    path("fetch_provider/", views.fetch_provider),
    path("fetch_user/", views.fetch_user),
    path("patient/create/", views.create_patient),
    path("patient/fetch/", views.fetch_patients),
    path("patient/fetch/<int:id>/", views.fetch_single_patient),
    path("patient/delete/<int:id>/", views.delete_patient),
    path("patient/fetch/<int:id>/generate_patient_json/<int:provider_account>/", views.generate_patient_json),
    path("patient/fetch/<int:id>/medication_history/", views.fetch_medication_history_records),
    path("patient/fetch/<int:id>/vaccination_history/", views.fetch_vaccination_history_records),
    path("patient/fetch/<int:id>/family_history/", views.fetch_family_history_records),
    path("patient/fetch/<int:id>/social_history/", views.fetch_social_history_records),
    path("patient/fetch/<int:id>/surgical_history/", views.fetch_surgical_history_records),
    path("patient/fetch/<int:id>/vital_history/", views.fetch_vital_history_records),
    path("patient/fetch/<int:id>/allergy_history/", views.fetch_allergy_history_records),
    path("patient/fetch/<int:id>/medication_history/<int:record_id>/", views.fetch_single_medication_history_record),
    path("patient/fetch/<int:id>/vaccination_history/<int:record_id>/", views.fetch_single_vaccination_history_record),
    path("patient/fetch/<int:id>/family_history/<int:record_id>/", views.fetch_single_family_history_record),
    path("patient/fetch/<int:id>/social_history/<int:record_id>/", views.fetch_single_social_history_record),
    path("patient/fetch/<int:id>/surgical_history/<int:record_id>/", views.fetch_single_surgical_history_record),
    path("patient/fetch/<int:id>/vital_history/<int:record_id>/", views.fetch_single_vital_history_record),
    path("patient/fetch/<int:id>/allergy_history/<int:record_id>/", views.fetch_single_allergy_history_record),
    path("patient/create/<int:id>/medication_history/", views.create_medication_history_record),
    path("patient/create/<int:id>/vaccination_history/", views.create_vaccination_history_record),
    path("patient/create/<int:id>/family_history/", views.create_family_history_record),
    path("patient/create/<int:id>/social_history/", views.create_social_history_record),
    path("patient/create/<int:id>/surgical_history/", views.create_surgical_history_record),
    path("patient/create/<int:id>/vital_history/", views.create_vital_history_record),
    path("patient/create/<int:id>/allergy_history/", views.create_allergy_history_record),
    path("patient/update/<int:id>/medication_history/<int:record_id>/", views.update_medication_history_record),
    path("patient/update/<int:id>/vaccination_history/<int:record_id>/", views.update_vaccination_history_record),
    path("patient/update/<int:id>/family_history/<int:record_id>/", views.update_family_history_record),
    path("patient/update/<int:id>/social_history/<int:record_id>/", views.update_social_history_record),
    path("patient/update/<int:id>/surgical_history/<int:record_id>/", views.update_surgical_history_record),
    path("patient/update/<int:id>/vital_history/<int:record_id>/", views.update_vital_history_record),
    path("patient/update/<int:id>/allergy_history/<int:record_id>/", views.update_allergy_history_record),
    path("patient/delete/<int:id>/medication_history/<int:record_id>/", views.delete_medication_history_record),
    path("patient/delete/<int:id>/vaccination_history/<int:record_id>/", views.delete_vaccination_history_record),
    path("patient/delete/<int:id>/family_history/<int:record_id>/", views.delete_family_history_record),
    path("patient/delete/<int:id>/social_history/<int:record_id>/", views.delete_social_history_record),
    path("patient/delete/<int:id>/surgical_history/<int:record_id>/", views.delete_surgical_history_record),
    path("patient/delete/<int:id>/vital_history/<int:record_id>/", views.delete_vital_history_record),
    path("patient/delete/<int:id>/allergy_history/<int:record_id>/", views.delete_allergy_history_record),
    
    path('patient/download-medical-records/<int:id>/', views.download_medical_records_pdf, name='download_medical_records_pdf'),


]
