# Generated by Django 5.1.2 on 2024-10-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birthday',
            field=models.DateField(default='1990-01-03'),
            preserve_default=False,
        ),
    ]
