# Generated by Django 5.1.2 on 2024-10-29 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_patient_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prescribed', models.DateField()),
                ('generic_name', models.CharField(max_length=30)),
                ('dosage_form', models.CharField(max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('instructions', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='Records',
        ),
    ]
