# Generated by Django 5.1.2 on 2024-11-02 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_dosage_form_medicationhistory_dosage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('date_administered', models.DateField()),
                ('vaccine_name', models.CharField(max_length=30)),
                ('provider', models.CharField(max_length=30)),
                ('site_given', models.CharField(max_length=30)),
                ('dose_ml', models.CharField(max_length=20)),
                ('next_dose_date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
