# Generated by Django 5.1.2 on 2024-11-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_vaccinationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationhistory',
            name='brand_name',
            field=models.CharField(default='Fluzone Quoxidote', max_length=30),
            preserve_default=False,
        ),
    ]
