# Generated by Django 5.1.2 on 2024-11-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_familyhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationhistory',
            name='date_added',
            field=models.DateField(default='2024-11-02'),
            preserve_default=False,
        ),
    ]
