# Generated by Django 5.1.2 on 2024-11-02 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_medicationhistory_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('nicotine_consumption', models.CharField(max_length=50)),
                ('alcohol_consumption', models.CharField(max_length=50)),
                ('drugs_taken', models.CharField(max_length=30)),
                ('diet', models.CharField(max_length=100)),
                ('physical_activity', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
