# Generated by Django 5.1.2 on 2024-11-13 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_socialhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('operation_procedure', models.CharField(max_length=50)),
                ('indication', models.CharField(max_length=50)),
                ('hospital', models.CharField(max_length=50)),
                ('operation_date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
