# Generated by Django 5.1.2 on 2024-11-13 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_surgicalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('temperature', models.CharField(max_length=20)),
                ('blood_pressure', models.CharField(max_length=20)),
                ('pulse_rate', models.CharField(max_length=20)),
                ('blood_glucose', models.CharField(max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
