# Generated by Django 5.1.2 on 2024-11-13 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_vitalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('substance', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=30)),
                ('criticality', models.CharField(max_length=30)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
