# Generated by Django 5.1.2 on 2024-12-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_provider_provider_location_provider_provider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationhistory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
