# Generated by Django 5.1.2 on 2024-12-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_patient_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='provider_city',
            field=models.CharField(default='Cebu City', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='provider_contact_number',
            field=models.CharField(default='09664139289', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='provider_email',
            field=models.EmailField(default='pewdiestuff@gmail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='provider_province',
            field=models.CharField(default='Cebu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='provider_region',
            field=models.CharField(default='Region 7 - Visayas Region', max_length=100),
            preserve_default=False,
        ),
    ]
