# Generated by Django 5.1.2 on 2024-12-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_provider_provider_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_pictures/'),
        ),
    ]
